### ISSUE TITLE
installation field does not exist.

### ISSUE THREAD

**Issue by luisschubert** [bkeepers/github-integration-example#6]
I'm trying to follow along the example, and getting the webhook and console logging a new issue is working.

```
handler.on('issues', function (event) {
  if (event.payload.action === 'opened') {
    var installation = event.payload.installation.id;

    app.asInstallation(installation).then(function (github) {
      github.issues.createComment({
        owner: event.payload.repository.owner.login,
        repo: event.payload.repository.name,
        number: event.payload.issue.number,
        body: 'Welcome to the robot uprising.'
      });
    });
  }
});
```

Error:
```
Received an issue event for webhookTest action=opened: #17 Still wanting to speak to a bot...
/Users/luisschubert/dev/github-app-example/index.js:21
        var installation = event.payload.installation.id;
                                                     ^

TypeError: Cannot read property 'id' of undefined
    at EventEmitter.<anonymous> (/Users/luisschubert/dev/github-app-example/index.js:21:54)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at BufferList._callback (/Users/luisschubert/dev/github-app-example/node_modules/github-webhook-handler/github-webhook-handler.js:97:15)
    at BufferList.end (/Users/luisschubert/dev/github-app-example/node_modules/bl/bl.js:98:10)
    at IncomingMessage.onend (_stream_readable.js:511:10)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)

```

@bkeepers  would appreciate a comment.

**Comment by luisschubert** [comment]
Seems like you are listening to installation of the app to the repository. no wonder that field was not present when i'm listening to issues.
